services:
  frontend:
    build:
      context: ./frontend # Next.js Dockerfile 경로
      dockerfile: Dockerfile
    image: mcpanda-frontend:latest
    container_name: mcpanda_frontend_container
    restart: always
    networks:
      - app_network
    # environment: # 필요시 환경 변수
    # ports: # Nginx를 통하므로 직접 노출은 선택 사항
    #   - "3000:3000"

  nginx_proxy:
    image: nginx:stable-alpine
    container_name: mcpanda_nginx_proxy_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      # - springboot_app
    networks:
      - app_network

networks:
  app_network: # <--- "app_network" 라는 이름의 사용자 정의 네트워크를 선언합니다.
    driver: bridge # <--- 이 네트워크가 어떤 종류의 네트워크 드라이버를 사용할지 지정합니다.